# -*- coding: utf-8 -*-
"""bank.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dZolV_W0VAeIgLopItA10gkGdpc185hL
"""

class bank_account:
    def __init__(self,user_n,user_p,bal):
        self.user_n=user_n
        self.user_p=user_p
        self.bal=bal
  #Account Login method
    def login(self,check_username,check_pin):
        self.check_user=check_username
        self.check_pin=check_pin
        if((self.user_n==self.check_user)&(self.user_p==check_pin)):
          print("\n Login successfull!\n")
          return True
        else:
          print("Invalide user name or password")
          return False
   #Amount Deposit method
    def deposit(self,deposit_amt):
        self.deposit=deposit_amt
        self.bal=self.bal+self.deposit
        print("Rs.",self.deposit," deposited successfuly\n")
        return self.bal
    #Amount Withdrawal method
    def withdraw(self,withdraw_amt):
        self.withdraw_amt=withdraw_amt
        if(self.bal<self.withdraw_amt):
            print("\nInsufficient balance to withdraw\nCurrent balance is\n",self.bal)
        else:
            self.bal=self.bal-self.withdraw_amt
            print("Rs.",self.withdraw_amt," withdrew successfuly\n")
            print("\nNew balance is:",self.bal,"\n____________________________")
            return self.bal


account=bank_account("john","1234",5000)
print("Hello........ Welcome to ABC Bank")
print("____________________________")
check_username=input("Enter the user name: ").lower() #assuming user name is not case sensitive
check_pin=input("Enter the pin: ")
print("____________________________")
z=1
while(z==1):
  if account.login(check_username,check_pin):
     x=input("1: Amount Deposit\n2: Amount Withdrawal\n")
     print("\n_____________________________")
     if(x=="1"):
         i=float(input("\nEnter the deposit amount\n"))
         if(i>0):
             balance=account.deposit(i)
             print("\nNew balance is:",balance,"\n___________________________")
         else:
             print("\nEnter a valid amount to deposit")
     elif(x=="2"):
         j=float(input("Enter the withdrawal amount\n"))
         balance=account.withdraw(j)
  else:
    break
  z=float(input("Enter 1 to continue or any other key  to exit: "))
print("Thank you!\n______________________")